{{- range $index, $gateway := .Values.gateways }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ $gateway.name }}
spec:
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range $index, $vservice := $gateway.vservices }}
    - "{{ $vservice.host }}"
    {{- end }}
    tls:
      httpsRedirect: true
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ $gateway.tlsSecret }}
    hosts:
    {{- range $index, $vservice := $gateway.vservices }}
    - "{{ $vservice.host }}"
    {{- end }}
---
{{- end }}
