{{- range $index, $gateway := .Values.gateways }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-{{ $gateway.tlsSecret }}
spec:
  destination:
    create: true
    name: {{ $gateway.tlsSecret }}
    type: kubernetes.io/tls
  mount: {{ $.Values.vault.serviceMountName }}
  path: {{ $gateway.tlsSecret }}
  type: kv-v2

---
{{- end }}
