defaultNamespace: istio-system
helm:
  repo: https://istio-release.storage.googleapis.com/charts
  chart: istiod
  releaseName: istiod
  values:
    istio_cni.enabled: true
    pilot.autoscaleEnabled: false

dependsOn:
  - name: mekstack-deps-k8s-deps-istio-istio-cni
