---
- name: Ensure /etc/hosts has fqdns
  hosts: all
  become: true
  tasks:
    - ansible.builtin.blockinfile:
        block: |
         {{ kolla_external_vip_address }} {{ kolla_external_fqdn }}
         {{ kolla_internal_vip_address }} {{ kolla_internal_fqdn }}
         {{ kolla_external_vip_address }} cinder.api.mekstack.ru
         {{ kolla_external_vip_address }} nova.api.mekstack.ru
         {{ kolla_external_vip_address }} placement.api.mekstack.ru
         {{ kolla_external_vip_address }} keystone.api.mekstack.ru
         {{ kolla_external_vip_address }} magnum.api.mekstack.ru
         {{ kolla_external_vip_address }} octavia.api.mekstack.ru
         {{ kolla_external_vip_address }} heat.api.mekstack.ru
         {{ kolla_external_vip_address }} designate.api.mekstack.ru
         {{ kolla_external_vip_address }} neutron.api.mekstack.ru
         {{ kolla_external_vip_address }} glance.api.mekstack.ru
         {{ kolla_external_vip_address }} heat-cfn.api.mekstack.ru
         {{ kolla_external_vip_address }} barbican.api.mekstack.ru
         172.18.222.6 kayobe.mekstack.ru
         172.18.217.1 vault.mekstack.ru
        dest: /etc/hosts
        marker: "# {mark} ANSIBLE MANAGED API ENDPOINTS"
