---
- name: Ensure /etc/hosts has fqdns
  hosts: all
  become: true
  tasks:
  - lineinfile:
      dest: /etc/hosts
      regexp: ".*{{ item.fqdn }}"
      line: "{{ item.vip }} {{ item.fqdn }}"
      state: present
    loop:
      - { vip: "{{ kolla_external_vip_address }}", fqdn: "{{ kolla_external_fqdn }}" }
      - { vip: "{{ kolla_internal_vip_address }}", fqdn: "{{ kolla_internal_fqdn }}" }
      - { vip: "172.18.222.6", fqdn: "kayobe.mekstack.ru" }
