---
- name: Configure control plane monitoring for Grafana
  # Only required to run on a single host.
  hosts: monitoring[0]
  tags:
    - grafana
  pre_tasks:
    - name: Include Kolla passwords for Grafana local admin account credentials
      include_vars: "/etc/kolla/passwords.yml"
  roles:
    - role: stackhpc.grafana-conf
      grafana_conf_organisation: "{{ grafana_control_plane_organisation }}"
      grafana_conf_grafana_admin_user: "{{ grafana_local_admin_user_name }}"
      grafana_conf_grafana_admin_pass: "{{ grafana_admin_password }}"
      grafana_conf_grafana_dashboard_repo:
        repo: "{{ grafana_monitoring_node_dashboard_repo }}"
        version: "{{ grafana_monitoring_node_dashboard_repo_version }}"
        checkout_path: "{{ grafana_monitoring_node_dashboard_repo_checkout_path }}"
        relative_path: "{{ grafana_monitoring_node_dashboard_repo_path }}"
      grafana_conf_grafana_url: "https://{{ kolla_internal_fqdn }}:3000"
      grafana_conf_grafana_datasources: "{{ grafana_datasources }}"
      grafana_conf_grafana_datasource_definitions:
        prometheus: |
          {
          "access": "proxy",
          "basicAuth": false,
          "basicAuthPassword": "",
          "basicAuthUser": "",
          "database": "",
          "isDefault": false,
          "jsonData": {
             "keystoneAuth": true
          },
          "name": "Prometheus",
          "password": "",
          "type": "prometheus",
          "url": "http://{{ datasource.host }}:{{ datasource.port }}/",
          "user": "",
          "withCredentials": false
          }
