---
- name: Copy IdP configuration
  hosts: localhost
  tasks:
  - name: Copy IdP client configuration
    ansible.builtin.template:
      src: "{{ kayobe_config_path }}/kolla/templates/federation/client.j2"
      dest: "{{ kayobe_config_path }}/kolla/federation/idp/vault.mekstack.ru%2Fv1%2Fidentity%2Foidc%2Fprovider%2Fhse.client"
