#cloud-config
package_update: true
packages:
  - nginx
  - iptables-persistent

write_files:
  - path: /etc/nginx/nginx.conf
    permissions: '0644'
    owner: root:root
    content: |
      worker_processes auto;
      load_module /usr/lib/nginx/modules/ngx_stream_module.so;

      events {
          worker_connections  1024;
      }

      stream {
          access_log off;
          error_log /dev/null;

          map $ssl_preread_server_name $target {
              # Exceptions to be routed to a VLAN 217
              mekstack.ru 172.18.217.200:443;
              status.mekstack.ru 172.18.217.200:443;
              cinder.api.mekstack.ru 172.18.217.200:443;
              nova.api.mekstack.ru 172.18.217.200:443;
              placement.api.mekstack.ru 172.18.217.200:443;
              keystone.api.mekstack.ru 172.18.217.200:443;
              octavia.api.mekstack.ru 172.18.217.200:443;
              heat.api.mekstack.ru 172.18.217.200:443;
              designate.api.mekstack.ru 172.18.217.200:443;
              neutron.api.mekstack.ru 172.18.217.200:443;
              glance.api.mekstack.ru 172.18.217.200:443;
              heat-cfn.api.mekstack.ru 172.18.217.200:443;
              novncproxy.api.mekstack.ru 172.18.217.200:443;

              # Default behavior: dns lookup
              default $ssl_preread_server_name:443;
          }

          server {
              resolver 172.18.218.200;
              listen 443;
              ssl_preread on;
              proxy_pass $target;
              proxy_connect_timeout 60s;
          }
      }

      http {
          access_log off;
          error_log /dev/null;

          server {
              resolver 172.18.218.200;

              listen 80;
              server_name _;
              client_max_body_size 1000m;

              location / {
                  set $backend "http://$host";

                  proxy_pass $backend;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_connect_timeout 10s;
                  proxy_http_version 1.1;
              }
          }
      }

runcmd:
  - systemctl enable nginx
  - systemctl restart nginx

  - iptables -A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
  - iptables -A OUTPUT -d 172.18.218.0/23 -j ACCEPT
  - iptables -A OUTPUT -d 172.18.217.0/24 -j ACCEPT
  - iptables -A OUTPUT -j REJECT --reject-with icmp-net-unreachable

  - iptables-save > /etc/iptables/rules.v4
