{{- range $index, $vservice := .Values.vservices }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $vservice.name }}
spec:
  hosts:
  - {{ $vservice.host }}
  gateways:
  - {{ $.Values.externalGateway }}
  http:
  - name: http-{{ $vservice.name }}
    route:
    - destination:
        host: {{ $vservice.destination | quote }}
        {{- if hasKey $vservice "portNumber"}}
        port:
          number: {{$vservice.portNumber}}
        {{- end}}
    match:
      - uri:
          prefix: {{ $vservice.matchUriPrefix }}
---
{{- end }}

