---

- name: Include drone secrets
  set_fact:
     "{{ item }}": "{{ lookup('hashi_vault', 'secret=kv/data/drone:{{ item }}') }}"
  with_items: "{{ setup_secrets }}"
  vars:
    setup_secrets:
      - client_id
      - client_secret
      - shared_secret



