- name: Deploy Docker Registry
  hosts: registries
  become: yes
  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: "docker.io"
        state: "present"

    - name: Start the Docker service
      ansible.builtin.service:
        name: "docker"
        state: "started"
        enabled: yes

    - name: Install Docker Compose
      ansible.builtin.apt:
        name: "docker-compose"
        state: "present"
        
    - name: Create a directory for Docker Registry
      ansible.builtin.file:
        path: "/opt/registry"
        state: "directory"

    - name: Generate Docker Compose file for Registry
      ansible.builtin.template:
        src: "registry/docker-compose.yml"
        dest: "/opt/registry/docker-compose.yml"

    - name: Start Docker Registry
      community.docker.docker_compose:
        project_src: "/opt/registry"
        files:
        - docker-compose.yml
        