version: '3'

services:
  registry:
    image: registry:2
    container_name: docker_registry
    restart: always   # Добавляем опцию для автоматического перезапуска контейнера
    ports:
      - "5000:5000"
    volumes:
      - /opt/registry/data:/var/lib/registry
