defaultNamespace: istio-ingress
helm:
  repo: https://istio-release.storage.googleapis.com/charts
  chart: gateway
  releaseName: istio-ingress

dependsOn:
  - name: mekstack-k8s-istio-istio-base
  - name: mekstack-k8s-istio-istiod
