apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: docs
  namespace: fleet-local
spec:
  repo: https://github.com/mekstack/docs
  paths:
  - manifests
---
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: compliance-docs
  namespace: fleet-local
spec:
  repo: https://github.com/mekstack/compliance-docs
  paths:
  - manifests
