---
- name: Build latest docs
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: Ensure docs source code checkout exists
      git: 
        repo: 'https://github.com/mekstack/docs'
        dest: "{{ docs_checkout_path }}"

    - name: Compile docs html
      shell: 
        cmd: tox -- html
        chdir: "{{ docs_checkout_path }}"

- name: Configure nginx
  hosts: all
  become: true
  tasks:
    - name: Update repositories
      apt:
        update_cache: yes

    - name: Install packages
      apt:
        name: "{{ item }}"
      with_items:
        - nginx
        - rsync

    - name: Enable and start nginx
      service:
        name: nginx
        enabled: yes

- name: Deploy docs
  hosts: all
  become: true
  tasks:
    - name: Copy nginx.conf
      template:
        src: 'nginx.conf'
        dest: '/etc/nginx/nginx.conf'

    - name: Verify nginx config
      shell: nginx -t
      register: out
    - debug:
        msg: '{{ out.stdout_lines }}, {{ out.stderr_lines }}'

    - name: Ensure /var/www/ exists
      file:
        path: /var/www
        state: directory
        owner: 1000
        group: 1000
        mode: 0775

    - name: Copy built files
      synchronize:
        src: "{{ docs_checkout_path }}/build/html/"
        dest: '/var/www/html/'
        recursive: yes
        rsync_opts: ['--chown', '1000:1000', '--chmod', '0775']

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
