---
- name: Deploy new docs
  hosts: all
  tasks:
    - name: Check env
      fail:
        msg: "Environment variable DOCS_ROOT is not defined or empty"
      when: lookup('env', 'DOCS_ROOT') == ''

    - name: Update repositories
      become: yes
      community.general.pacman:
        update_cache: yes

    - name: Install nginx
      become: yes
      community.general.pacman:
        name: nginx

    - name: Install rsync
      become: yes
      community.general.pacman:
        name: rsync

    - name: Enable and start nginx
      become: yes
      service:
        name: nginx
        enabled: yes
        args: now

    - name: Copy nginx.conf
      become: yes
      template:
        src: 'nginx.conf'
        dest: '/etc/nginx/nginx.conf'

    - name: Verify nginx config
      become: yes
      shell: nginx -t
      register: out
    - debug:
        msg: '{{ out.stdout_lines }}, {{ out.stderr_lines }}'

    - name: Ensure /var/www/ exists
      become: true
      file:
        path: /var/www
        state: directory
        owner: arch
        group: arch
        mode: 0775

    - name: Copy built files
      become: false
      synchronize:
        src: "{{ lookup('env', 'DOCS_ROOT') }}/build/html/"
        dest: '/var/www/html/'
        recursive: yes

    - name: Change /var/www/ permissions
      become: true
      file:
        path: /var/www
        state: directory
        owner: arch
        group: arch
        mode: 0775
        recurse: true

    - name: Restart nginx
      become: yes
      service:
        name: nginx
        state: restarted
